services:
  db:
    image: postgres:17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
