name: Lint with Flake8

on:
  # Run this workflow on pushes to any branch and on pull requests
  push:
    branches:
      - "**"

jobs:
  lint-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python version, like '3.9' or '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./backend

      # Run flake8 linter
      - name: Run flake8
        run: |
          python -m pip install flake8
          flake8
        working-directory: ./backend
